### ISSUE TITLE
Error when using the extension

### ISSUE THREAD

**Issue by arjuns2020** [jdfenton/extract-sql-from-script#1] opened 2020-07-18 05:29 UTC
![image](https://user-images.githubusercontent.com/13196766/87845481-1b277e00-c885-11ea-9124-14a788b8b4f4.png)

![image](https://user-images.githubusercontent.com/13196766/87845513-51fd9400-c885-11ea-9425-2dac70ef3a81.png)

Command failed: file -L -b --mime-type c:\Users\751530\Documents\python 3 upgraded - changing postgre syntax\e3.py 'file' is not recognized as an internal or external command, operable program or batch file.

**Comment by jdfenton** [comment] 2020-07-18 06:12
Thanks for sharing.

Looks like the second error is coming from a different extension (Linux Binary Preview), however the first error is from the SQL extractor.

Can you pls share a sample Py file that causes this error?

Would like to see if it can be reproduced with the same input file, or if it's environment specific.

**Comment by jdfenton** [comment] 2020-07-20 12:05
Hi Arjun, following up on this one. So I can investigate further, can you provide a sample input file that causes this error for you?

I'm keen to get it fixed up for you.

As it stands, my one and only review on VS Marketplace is your 1-star review... 🤕

**Comment by jdfenton** [comment] 2020-07-27 01:51
Closing this issue as not enough detail was provided to replicate this issue.

One error comes from a different extension, and the other strongly suggests the input file was not in the required format (as documented in the read-me page).

I'm happy to take suggestions or feedback to enhance the extension if you do get back in touch.

It's a shame you had to raise this as a review, rather than a Q&A or GitHub issue.

**Closed by jdfenton** 2020-07-27 01:51 UTC
Labels: invalid
